# LLM Finetuning Script
An LLM (Large Language Model) fine-tuning script is a program designed to adapt a pre-trained language model to a specific task or domain. It does this by training the model on a smaller, more focused dataset,allowing it to specialize and improve its performance in the desired area.

## Download the Libraries

In [4]:
!pip install -U openai

Requirement already satisfied: openai in d:\setups\anaconda3\lib\site-packages (1.52.2)
Requirement already satisfied: anyio<5,>=3.5.0 in d:\setups\anaconda3\lib\site-packages (from openai) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in d:\setups\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\setups\anaconda3\lib\site-packages (from openai) (0.27.0)
Requirement already satisfied: jiter<1,>=0.4.0 in d:\setups\anaconda3\lib\site-packages (from openai) (0.6.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in d:\setups\anaconda3\lib\site-packages (from openai) (2.5.3)
Requirement already satisfied: sniffio in d:\setups\anaconda3\lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in d:\setups\anaconda3\lib\site-packages (from openai) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.11 in d:\setups\anaconda3\lib\site-packages (from openai) (4.11.0)
Requirement already satisfied: idna>=2.8 in d:\setups\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in d:\setups\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2024.8.30)
Requirement already satisfied: httpcore==1.* in d:\setups\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in d:\setups\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in d:\setups\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in d:\setups\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.14.6)
Requirement already satisfied: colorama in d:\setups\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)

## Import OpenAI

In [6]:
from openai import OpenAI
client = OpenAI(api_key="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")

## Simple API Request for OPEN AI

In [8]:
completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)

print(completion.choices[0].message)

ChatCompletionMessage(content="In the realm of code, a concept is found,\nRecursive magic, turning wheels around.\nA function calls itself, in daring delight,\nCascading through layers, like stars in the night.\n\nWith elegance and grace, it dances through,\nSolving problems complex, old and new.\nLike a Russian doll, nested and deep,\nIt delves into tasks that make us leap.\n\nA loop within a loop, a mirror's reflection,\nRecursion whispers endless perfection.\nWith each call it shrinks the problem at hand,\nTill solutions emerge, like grains of sand.\n\nSo heed the call of recursion's sweet song,\nEmbrace its power, swift and strong.\nFor in the realm of code, where wonders daunt,\nRecursion reigns, a mystical font.", refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None)

## Import Dataset and create Testing Dataset

In [32]:
import pandas as pd
df = pd.read_csv("employee_rating.csv")
df.head(40)

,prompt,rate,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"Role: Software Intern, User Description: I'm i...",Moderate,NaN,NaN,NaN,NaN,NaN
1,"Role: Software Intern, User Description: Curre...",Moderate,NaN,NaN,NaN,NaN,NaN
2,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
3,"Role: Software Engineer, User Description: Cur...",Moderate,NaN,NaN,NaN,NaN,NaN
4,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
5,"Role: Technical Lead, User Description: With o...",Moderate,NaN,NaN,NaN,NaN,NaN
6,"Role: Technical Lead, User Description: With 6...",Moderate,NaN,NaN,NaN,NaN,NaN
7,"Role: Technical Lead, User Description: I brin...",Moderate,NaN,NaN,NaN,NaN,NaN
8,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
9,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
10,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
11,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
12,Role: Technical Lead\nUser Description: My lea...,good,NaN,NaN,NaN,NaN,NaN
13,Role: Technical Lead\nUser Description: Taking...,good,NaN,NaN,NaN,NaN,NaN
14,Role: Software Architect\nUser Description: Cr...,good,NaN,NaN,NaN,NaN,NaN
15,Role: Software Architect\nUser Description: Sp...,good,NaN,NaN,NaN,NaN,NaN
16,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
17,Role: Software Architect\nUser Description: Wi...,good,NaN,NaN,NaN,NaN,NaN
18,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
19,Role: Technical Lead\nUser Description: Experi...,good,NaN,NaN,NaN,NaN,NaN
20,Role: Technical Lead\nUser Description: With e...,good,NaN,NaN,NaN,NaN,NaN
21,Role: Software Engineer\nUser Description: Sea...,good,NaN,NaN,NaN,NaN,NaN
22,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
23,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
24,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
25,"Role: Software Intern, User Description: I jus...",Bad,NaN,NaN,NaN,NaN,NaN
26,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN
27,"Role: Software Intern, User Description: I did...",Bad,NaN,NaN,NaN,NaN,NaN
28,"Role: Software Intern, User Description: I'm o...",Bad,NaN,NaN,NaN,NaN,NaN
29,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN
30,"Role: Software Engineer, User Description: I'm...",Bad,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_head = df.head(10)
df_head.to_csv("employee_rating_test.csv", index=False)
df_head.head(10)

,prompt,rate,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"Role: Software Engineer, User Description: As ...",Bad,NaN,NaN,NaN,NaN,NaN
1,"Role: Software Engineer, User Description: Wit...",Bad,NaN,NaN,NaN,NaN,NaN
2,"Role: Software Engineer, User Description: I'm...",Bad,NaN,NaN,NaN,NaN,NaN
3,"Role: Software Engineer, User Description: Cur...",Bad,NaN,NaN,NaN,NaN,NaN
4,"Role: Technical Lead, User Description: I have...",Bad,NaN,NaN,NaN,NaN,NaN
5,"Role: Technical Lead, User Description: With 1...",Bad,NaN,NaN,NaN,NaN,NaN
6,"Role: Technical Lead, User Description: I brin...",Bad,NaN,NaN,NaN,NaN,NaN
7,"Role: Technical Lead, User Description: Curren...",Bad,NaN,NaN,NaN,NaN,NaN
8,"Role: Technical Lead, User Description: I'm an...",Bad,NaN,NaN,NaN,NaN,NaN
9,"Role: Software Intern, User Description: Recen...",Moderate,NaN,NaN,NaN,NaN,NaN

In [34]:
df_head.head(20)

,prompt,rate,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"Role: Software Engineer, User Description: As ...",Bad,NaN,NaN,NaN,NaN,NaN
1,"Role: Software Engineer, User Description: Wit...",Bad,NaN,NaN,NaN,NaN,NaN
2,"Role: Software Engineer, User Description: I'm...",Bad,NaN,NaN,NaN,NaN,NaN
3,"Role: Software Engineer, User Description: Cur...",Bad,NaN,NaN,NaN,NaN,NaN
4,"Role: Technical Lead, User Description: I have...",Bad,NaN,NaN,NaN,NaN,NaN
5,"Role: Technical Lead, User Description: With 1...",Bad,NaN,NaN,NaN,NaN,NaN
6,"Role: Technical Lead, User Description: I brin...",Bad,NaN,NaN,NaN,NaN,NaN
7,"Role: Technical Lead, User Description: Curren...",Bad,NaN,NaN,NaN,NaN,NaN
8,"Role: Technical Lead, User Description: I'm an...",Bad,NaN,NaN,NaN,NaN,NaN
9,"Role: Software Intern, User Description: Recen...",Moderate,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.iloc[10:] 
df.to_csv("employee_rating.csv", index=False)
df.head(30)

,prompt,rate,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
10,"Role: Software Intern, User Description: I'm i...",Moderate,NaN,NaN,NaN,NaN,NaN
11,"Role: Software Intern, User Description: Curre...",Moderate,NaN,NaN,NaN,NaN,NaN
12,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
13,"Role: Software Engineer, User Description: Cur...",Moderate,NaN,NaN,NaN,NaN,NaN
14,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
15,"Role: Technical Lead, User Description: With o...",Moderate,NaN,NaN,NaN,NaN,NaN
16,"Role: Technical Lead, User Description: With 6...",Moderate,NaN,NaN,NaN,NaN,NaN
17,"Role: Technical Lead, User Description: I brin...",Moderate,NaN,NaN,NaN,NaN,NaN
18,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
19,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
20,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
21,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
22,Role: Technical Lead\nUser Description: My lea...,good,NaN,NaN,NaN,NaN,NaN
23,Role: Technical Lead\nUser Description: Taking...,good,NaN,NaN,NaN,NaN,NaN
24,Role: Software Architect\nUser Description: Cr...,good,NaN,NaN,NaN,NaN,NaN
25,Role: Software Architect\nUser Description: Sp...,good,NaN,NaN,NaN,NaN,NaN
26,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
27,Role: Software Architect\nUser Description: Wi...,good,NaN,NaN,NaN,NaN,NaN
28,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
29,Role: Technical Lead\nUser Description: Experi...,good,NaN,NaN,NaN,NaN,NaN
30,Role: Technical Lead\nUser Description: With e...,good,NaN,NaN,NaN,NaN,NaN
31,Role: Software Engineer\nUser Description: Sea...,good,NaN,NaN,NaN,NaN,NaN
32,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
33,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
34,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
35,"Role: Software Intern, User Description: I jus...",Bad,NaN,NaN,NaN,NaN,NaN
36,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN
37,"Role: Software Intern, User Description: I did...",Bad,NaN,NaN,NaN,NaN,NaN
38,"Role: Software Intern, User Description: I'm o...",Bad,NaN,NaN,NaN,NaN,NaN
39,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN

In [43]:
# Drop rows with NaN values
df_cleaned = df.dropna()


# Check the cleaned data
print(df_cleaned.head(40))

Empty DataFrame
Columns: [prompt, rate, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6]
Index: []

In [38]:
df.head(60)

,prompt,rate,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"Role: Software Intern, User Description: I'm i...",Moderate,NaN,NaN,NaN,NaN,NaN
1,"Role: Software Intern, User Description: Curre...",Moderate,NaN,NaN,NaN,NaN,NaN
2,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
3,"Role: Software Engineer, User Description: Cur...",Moderate,NaN,NaN,NaN,NaN,NaN
4,"Role: Software Engineer, User Description: I'm...",Moderate,NaN,NaN,NaN,NaN,NaN
5,"Role: Technical Lead, User Description: With o...",Moderate,NaN,NaN,NaN,NaN,NaN
6,"Role: Technical Lead, User Description: With 6...",Moderate,NaN,NaN,NaN,NaN,NaN
7,"Role: Technical Lead, User Description: I brin...",Moderate,NaN,NaN,NaN,NaN,NaN
8,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
9,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
10,"Role: Software Architect, User Description: Wi...",Moderate,NaN,NaN,NaN,NaN,NaN
11,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
12,Role: Technical Lead\nUser Description: My lea...,good,NaN,NaN,NaN,NaN,NaN
13,Role: Technical Lead\nUser Description: Taking...,good,NaN,NaN,NaN,NaN,NaN
14,Role: Software Architect\nUser Description: Cr...,good,NaN,NaN,NaN,NaN,NaN
15,Role: Software Architect\nUser Description: Sp...,good,NaN,NaN,NaN,NaN,NaN
16,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
17,Role: Software Architect\nUser Description: Wi...,good,NaN,NaN,NaN,NaN,NaN
18,Role: Software Architect\nUser Description: Ac...,good,NaN,NaN,NaN,NaN,NaN
19,Role: Technical Lead\nUser Description: Experi...,good,NaN,NaN,NaN,NaN,NaN
20,Role: Technical Lead\nUser Description: With e...,good,NaN,NaN,NaN,NaN,NaN
21,Role: Software Engineer\nUser Description: Sea...,good,NaN,NaN,NaN,NaN,NaN
22,Role: Software Engineer\nUser Description: Wit...,good,NaN,NaN,NaN,NaN,NaN
23,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
24,Role: Software Engineering Intern\nUser Descri...,good,NaN,NaN,NaN,NaN,NaN
25,"Role: Software Intern, User Description: I jus...",Bad,NaN,NaN,NaN,NaN,NaN
26,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN
27,"Role: Software Intern, User Description: I did...",Bad,NaN,NaN,NaN,NaN,NaN
28,"Role: Software Intern, User Description: I'm o...",Bad,NaN,NaN,NaN,NaN,NaN
29,"Role: Software Intern, User Description: I don...",Bad,NaN,NaN,NaN,NaN,NaN
30,"Role: Software Engineer, User Description: I'm...",Bad,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Convert Rows to GPT Interpreting Format

In [30]:
def convert_to_gpt35_format(dataset):
    fine_tuning_data = []
    for _, row in dataset.iterrows():
        json_response = '{"rate": "' + row['rate'] + '"}' 
        fine_tuning_data.append({
            "messages": [
                {"role": "user", "content": row['prompt']},
                {"role": "assistant", "content": json_response}
            ]
        })
    return fine_tuning_data

dataset = pd.read_csv('employee_rating.csv')
converted_data = convert_to_gpt35_format(dataset)
converted_data

TypeError: can only concatenate str (not "float") to str

In [18]:
import json
json.loads(converted_data[0]['messages'][-1]['content'])

{'rate': 'Bad'}

## Test Train Spint

In [21]:
from sklearn.model_selection import train_test_split

# Stratified splitting. Assuming 'Top Category' can be used for stratification
train_data, val_data = train_test_split(
    converted_data,
    test_size=0.2,
    stratify=dataset['rate'],
    random_state=42  # for reproducibility
)

## Convert the Array to JSON Format

In [22]:
def write_to_jsonl(data, file_path):
    with open(file_path, 'w') as file:
        for entry in data:
            json.dump(entry, file)
            file.write('\n')


training_file_name = "train.jsonl"
validation_file_name = "val.jsonl"

write_to_jsonl(train_data, training_file_name)
write_to_jsonl(val_data, validation_file_name)

In [23]:
training_file = client.files.create(
    file=open(training_file_name, "rb"), purpose="fine-tune"
)
validation_file = client.files.create(
    file=open(validation_file_name, "rb"), purpose="fine-tune"
)

print("Training file id:", training_file.id)
print("Validation file id:", validation_file.id)

Training file id: file-2lTAiDq4pDtirVJBqntVhadc
Validation file id: file-AF6syvwv8upmRHMebnOB2nBz

## Run the below cell and wait for few hours to get the Build Job Completed

In [33]:
suffix_name = "fullstackTutorial"

response = client.fine_tuning.jobs.create(
    training_file=training_file.id,
    validation_file=validation_file.id,
    model="gpt-3.5-turbo",
    suffix=suffix_name,
)
response

FineTuningJob(id='ftjob-MZWpdUWT7TNG2eHCUHcKscid', created_at=1704434281, error=None, fine_tuned_model=None, finished_at=None, hyperparameters=Hyperparameters(n_epochs='auto', batch_size='auto', learning_rate_multiplier='auto'), model='gpt-3.5-turbo-0613', object='fine_tuning.job', organization_id='org-IiIKN0jLcjY7NoA3XECMH6Fg', result_files=[], status='validating_files', trained_tokens=None, training_file='file-Fsk7wAy8RBaI4OieDcSGZ2SR', validation_file='file-vVtLhqtjCdH8XTAzqypc6RmC')

## Get the Finetuned Model ID

In [43]:
responseModel = client.fine_tuning.jobs.retrieve("ftjob-Qmz2BUIEwNcIJYVxZ1tFxR9g")
responseModel

FineTuningJob(id='ftjob-Qmz2BUIEwNcIJYVxZ1tFxR9g', created_at=1704429684, error=None, fine_tuned_model='ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC', finished_at=1704430108, hyperparameters=Hyperparameters(n_epochs=3, batch_size=1, learning_rate_multiplier=2), model='gpt-3.5-turbo-0613', object='fine_tuning.job', organization_id='org-IiIKN0jLcjY7NoA3XECMH6Fg', result_files=['file-zoPH4H27dE5wPfjfZ50K4dVt'], status='succeeded', trained_tokens=7719, training_file='file-Fsk7wAy8RBaI4OieDcSGZ2SR', validation_file='file-vVtLhqtjCdH8XTAzqypc6RmC')

In [44]:
fine_tuned_model_id = responseModel.fine_tuned_model
print("\nFine-tuned model id:", fine_tuned_model_id)

Fine-tuned model id: ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC

## Make Test Prediction

In [27]:
def predict(test_messages, fine_tuned_model_id):

    response = client.chat.completions.create(
        model= fine_tuned_model_id, messages=test_messages
    )

    return response.choices[0].message.content

In [28]:
testSent = "Role: Software Engineer, User Description: With five years of experience in software engineering, I've successfully designed and implemented solutions to optimize efficiency and enhance user experiences. My achievements include spearheading the development of a critical module that increased application performance by 30%. Passionate about staying ahead in the tech landscape, I bring a wealth of knowledge in both frontend and backend development, aiming to contribute to innovative projects."

formatted_message = [
        {
            "role": "user",
            "content": "Role: Software Engineer, User Description: With five years of experience in software engineering, I've successfully designed and implemented solutions to optimize efficiency and enhance user experiences. My achievements include spearheading the development of a critical module that increased application performance by 30%. Passionate about staying ahead in the tech landscape, I bring a wealth of knowledge in both frontend and backend development, aiming to contribute to innovative projects."

        }
    ]

predict(formatted_message,"ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC")

'{"rate": "good"}'

## (Optional) Evaluate the Accuracy

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def format_test(row):

    formatted_message = [
        {
            "role": "user",
            "content": row['prompt']
        }
    ]
    return formatted_message


def predict(test_messages, fine_tuned_model_id):

    response = client.chat.completions.create(
        model=fine_tuned_model_id, messages=test_messages, temperature=0, max_tokens=50
    )

    return response.choices[0].message.content

In [16]:
def store_predictions(test_df, fine_tuned_model_id):

    print("fine_tuned_model_id",fine_tuned_model_id)
    test_df['Prediction'] = None

    for index, row in test_df.iterrows():
        test_message = format_test(row)
        prediction_result = predict(test_message, fine_tuned_model_id)
        test_df.at[index, 'Prediction'] = prediction_result

    test_df.to_csv("predictions.csv")

In [21]:

test_df = pd.read_csv("employee_rating_example.csv")
store_predictions(test_df, "ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC")

fine_tuned_model_id ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC

In [5]:
testSentence = "Role: Technical Lead, User Description: Im a senior engineer with just 1 year experince. I have programmed in 2 languages and I have worked previosly in 1 company"

completion = client.chat.completions.create(
  model="ft:gpt-3.5-turbo-0613:stemlink:fullstacktutorial:8dWQ9vUC",
  messages=[
    {"role": "user", "content": testSentence}
  ]
)

print(completion.choices[0].message.content) # "{"rate":"good"}"

{"rate": "Bad"}